'test'

diff --git a/demo1/Jenkinsfile b/demo1/Jenkinsfile
--- a/demo1/Jenkinsfile
+++ b/demo1/Jenkinsfile
@@ -36,7 +36,7 @@ pipeline {
                         echo 'delete current docker image'
                         echo "docker rmi 10.10.200.135:5000/${env.PROJECT_NAME}:${env.BUILD_ID}"
                         sh "docker rmi 10.10.200.135:5000/${env.PROJECT_NAME}:${env.BUILD_ID}"
-                    } else if(env.BRANCH_NAME == 'master') {
+                    } else if (env.BRANCH_NAME == 'master') {
                         dir('demo1/target') {
                             sh "mv ${env.PROJECT_NAME}.jar ${env.PROJECT_NAME}-${env.BUILD_ID}.jar"
                         }
@@ -65,13 +65,13 @@ pipeline {
                         echo 'no need to deploy'
                     } else if (env.BRANCH_NAME == 'master') {
                         dir('demo1/target') {
-                            sshPublisher(publishers: [sshPublisherDesc(configName: '10.10.200.135-GONGWEI', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: "ps -ef | grep pipeline | grep -v grep | awk '{print \"kill -9 \"\$2}'|sh\n" + // 杀掉之前的进程
+                            sshPublisher(failOnError: true, publishers: [sshPublisherDesc(configName: '10.10.200.135-GONGWEI', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: "ps -ef | grep pipeline | grep -v grep | awk '{print \"kill -9 \"\$2}'|sh\n" + // 杀掉之前的进程
                                     "cd /root/gongwei/pehr\n" +
                                     "rm -f ${env.PROJECT_NAME}-[!${BUILD_NUMBER}].jar\n" + // 删除之前的jar包,jenkins构建完成后会归档jar包,服务器上不需要留作备份
                                     "nohup java -Xmn512m -Xms1024m -Xmx2048m -Duser.timezone=GMT+08 -jar ${PROJECT_NAME}-${BUILD_NUMBER}.jar --server.port=6000 >/dev/null &\n" +
                                     "nohup java -Xmn512m -Xms1024m -Xmx2048m -Duser.timezone=GMT+08 -jar ${PROJECT_NAME}-${BUILD_NUMBER}.jar --server.port=6001 >/dev/null &\n" +
-                                    "./test.sh\n" +
-                                    "echo 123", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: 'pehr', remoteDirectorySDF: false, removePrefix: '', sourceFiles: '*.jar')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
+                                    "echo \"i am a failure\"" +
+                                    "exit 9", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: 'pehr', remoteDirectorySDF: false, removePrefix: '', sourceFiles: '*.jar')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
                         }
                     }
                 }
